const express = require('express')
const app = express()
const registerRouter = require('./routes/Register')
const loginRouter = require('./routes/login')
const {router} = require('./routes/Posts')
const FriendRequestRouter = require('./routes/FriendRequest')
const userProfileRouter = require('./routes/UserProfiles')
const authenticateUser = require('./middlewares/authenticateUser')
const cors = require('./middlewares/cors')
const connCheck = require('./middlewares/databaseConn')
require('dotenv').config()

app.use(cors)
app.use(connCheck)
app.use(express.json())
app.use(express.urlencoded({extended: false}))
app.use('/register', registerRouter)
app.use('/login', loginRouter)
//app.use(authenticateUser)
app.use('/posts', router)
app.use('/friendrequest',  FriendRequestRouter)
app.use('/userprofiles', userProfileRouter)

const PORT = process.env.PORT || 5000
app.listen(PORT,()=>{
    console.log(`app running on port ${PORT}`)
})
